<?php
// $Id$

/**
 * @file
 * Input filter that enhances oEmbed enabled URL:s with extra content
 */

//TODO: www subdomain independense for *.
//TODO: delete options on uninstall

/**
 * Implements hook_init().
 */
function oembed_init() {
  drupal_add_css(drupal_get_path('module', 'oembed') . '/oembed.css');
}

/**
 * Implements hook_help().
 */
function oembed_help($path, $arg) {
  switch ($path) {
    case 'admin/help#oembed':
      return '<p>' . t('Adds an input filter for replacing oEmbed enabled URL:s with embedded content') . '</p>';
  }
}

/**
 * Implements hook_filter_info().
 */
function oembed_filter_info() {
  $filters['oembed'] = array(
    'title' => t('oEmbed filter'),
    'description' => t('Embeds content for oEmbed-enabled web addresses and turns the rest, and e-mail addresses, into clickable links.'),
    'process callback' => 'oembed_filter_oembed_process',
    'settings callback' => 'oembed_filter_oembed_settings',
    'default settings' => array(
      'oembed_maxwidth' => '',
      'oembed_maxheight' => '',
    ),
  );
  return $filters;
}

/**
 * Implements hook_filter_FILTER_settings().
 */
function oembed_filter_oembed_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
  module_load_include('inc', 'oembed');
  return _oembed_filter_settings($form, $form_state, $filter, $format, $defaults);
}

/**
 * Implements hook_filter_FILTER_process().
 */
function oembed_filter_oembed_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  module_load_include('inc', 'oembed');
  return _oembed_filter_apply($text, $filter, $format, $langcode, $cache, $cache_id);
}
